[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit SH110X@^2.1.10
    adafruit/Adafruit NeoPixel@^1.12.0

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp32c3]
platform = espressif32
board = dfrobot_beetle_esp32c3

[env:pico_w]
platform = raspberrypi
board = rpipicow
